# project.yml

env:
  DATABASE_URL: ${DATABASE_URL}
  GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
  PUBLIC_API_URL: ${PUBLIC_API_URL}
  WEBSITE_URL: ${WEBSITE_URL}
  JWT_SECRET_RESET: ${JWT_SECRET_RESET}
  NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
  NEXTAUTH_URL: ${NEXTAUTH_URL}
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
  SMTP_PORT: ${SMTP_PORT}
  GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
  JWT_SECRET: ${JWT_SECRET}
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
  NEXT_PUBLIC_GA_ID: ${NEXT_PUBLIC_GA_ID}
  SMTP_PASS: ${SMTP_PASS}
  NEXT_PUBLIC_FIREBASE_API_KEY: ${NEXT_PUBLIC_FIREBASE_API_KEY}
  NEXT_PUBLIC_FIREBASE_APP_ID: ${NEXT_PUBLIC_FIREBASE_APP_ID}
  NODE_ENV: ${NODE_ENV}
  SMTP_HOST: ${SMTP_HOST}
  SMTP_USER: ${SMTP_USER}
